language: go

go:
  - 1.6.2

before_script:

install:
  - mkdir -p skeleton/src/github.com
  - ln -s $TRAVIS_BUILD_DIR/skeleton/gogo/ $TRAVIS_BUILD_DIR/skeleton/src/github.com/skeleton
  - export GOPATH=$GOPATH:$TRAVIS_BUILD_DIR/skeleton
  - go get -t -v ./...

script:
  - go test
